config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'homes#top'
  get 'about' => 'homes#about'

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :post_image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :body,
            presence: true,
            length: { maximum: 140 }
  validates :place_name, presence: true
  validates :difficult, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    # 投稿を全件取得
    @posts = Post.all
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿しました。"
      redirect_to post_path(@post.id), notice: "投稿しました。"
    else
      @user = current_user
      @posts = Post.all
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id), notice: "投稿を編集しました。"
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :place_name, :post_image, :difficult)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<% if @post.errors.any? %>
		<%= @post.errors.count %> errors
		<%= @post.errors.full_messages.each do |message| %>
		<%= message %>
		<% end %>
		<% end %>


		<h1 style="color: white;">編集画面</h1>

		<%= form_for(@post) do |f| %>

		<h4 style="color: white;">本文</h4>
		<%= f.text_area :body, style:"color:black;" %>

		<h4 style="color: white;">画像</h4>
		<%= f.attachment_field :post_image, style:"color:white;" %>

		<h4 style="color: white;">Place</h4>
		<%= f.text_area :place_name, style:"color:black;" %>

		<h4 style="color: white;">難易度</h4>
		<%= f.select :difficult, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], include_blank: "選択してください。", color: "black;" %><br><br>

		<%= f.submit '変更', class: "btn btn-primary" %>

		<% end %>

	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-8">
			<div style="color: white;">
				<table class="table table-hover table-inverse">
					<table style="table-layout: fixed; width: 100%" >
						<colgroup>
							<col style= "width: 25%;">
						</colgroup>
						<thead>
							<tr>
								<th>ユーザー</th>
								<th>本文</th>
								<th style="padding-left: 30px;">Place</th>
								<th style="padding-left: 30px;">難易度</th>
							</tr>
						</thead>
						<h1>投稿一覧</h1>
						<% @posts.each do |post| %>
						<tr>
							<td style="text-align: center;">
								<%= link_to user_path(post.user) do %>
								<%= attachment_image_tag post.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size:'60x60' %>
								<%= post.user.name %>
								<% end %>
							</td>
							<td style="word-wrap: break-word;">
								<%= link_to post.body, post_path(post.id) %>
							</td>
							<td style="word-wrap: break-word; padding-left: 30px;">
								<%= post.place_name %>
							</td>
							<td style="padding-left: 30px;">
								<%= post.difficult %>
							</td>
							<td>
								<%= post.post_comments.count %>件コメント
							</td>
							<td>
							</td>
						</tr>
						<% end %>
					</table>
				</table>
			</div>
		</div>
		<div class="col-xs-4">
			<h1 style="color: white;">新規投稿</h1>

			<%= form_for(@post, url: '/posts') do |f| %>

			<h4 style="color: white;">本文</h4>
			<%= f.text_area :body, style:"color:black;" %>

			<h4 style="color: white;">画像</h4>
			<%= f.attachment_field :post_image, style:"color:white;" %>

			<h4 style="color: white;">Place</h4>
			<%= f.text_area :place_name, style:"color:black;" %>

			<h4 style="color: white;">難易度</h4>
			<%= f.select :difficult, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], include_blank: "選択してください。", color: "black;" %><br><br>

			<%= f.submit 'ツイート', class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<h1 style="color: white;">新規投稿</h1>

		<div style="color: white;">
			<% if @post.errors.any? %>
			<%= @post.errors.count %> errors
			<%= @post.errors.full_messages.each do |message| %>
			<%= message %>
			<% end %>
			<% end %>
		</div>

		<%= form_for(@post, url: '/posts') do |f| %>

		<h4 style="color: white;">本文</h4>
		<%= f.text_area :body, style:"color:black;" %>

		<h4 style="color: white;">画像</h4>
		<%= f.attachment_field :post_image, style:"color:white;" %>

		<h4 style="color: white;">Place</h4>
		<%= f.text_area :place_name, style:"color:black;" %>

		<h4 style="color: white;">難易度</h4>
		<%= f.select :difficult, [["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"]], include_blank: "選択してください。", color: "black;" %><br><br>

		<%= f.submit 'ツイート', class: "btn btn-primary" %>

		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
o<div class="container">
	<div class="row">
		<div class="col-xs-2">
		</div>

		<div class="col-xs-8">
			<div style="color: white;">
				<% if flash[:notice] %>
				<p><%= flash[:notice] %></p>
				<% end %>


				<h2>ツイート</h2>
				<table class="table table-hover table-inverse">
					<table style="table-layout: fixed; width: 100%;">
						<colgroup>
							<col style="width: 30%;">
						</colgroup>
						<thead style="color: white;">
							<tr>
								<th>ユーザー</th>
								<th>投稿</th>
								<th style="padding-left: 30px;">場所</th>
								<th style="padding-left: 30px;">難易度</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<%= link_to user_path(@post.user) do %>
									<%= attachment_image_tag @post.user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size:'60x60' %><br>
									<%= @post.user.name %>
									<% end %>
								</td>
								<td style="word-wrap: break-word;">
									<%= @post.body %>
								</td>
								<td style="word-wrap: break-word; padding-left: 30px;">
									<%= @post.place_name %>
								</td>
								<td style="padding-left: 30px;">
									<%= @post.difficult %>
								</td>
								<% if current_user.admin? || (@post.user == current_user) %>
								<td>
									<%= link_to "編集", edit_post_path(@post.id) %>
								</td>
								<td>
									<%= link_to "削除", post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
								</td>
								<% end %>
							</tr>
							<table style="border:none;">
								<tr>
									<td>
										<%= attachment_image_tag @post, :post_image, :fill, 300, 300, format: 'jpeg' %>
									</td>
								</tr>
							</table>
						</tbody>
					</table>
				</table>

				<%= @post.created_at.strftime('%Y/%m/%d %H:%M') %>

				<% if @post.favorited_by?(current_user) %>
				<%= link_to post_favorite_path(@post), method: :delete do %>
				<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
				<%= @post.favorites.count %> いいね
				<% end %>
				<% else %>
				<%= link_to post_favorites_path(@post), method: :post do %>
				<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
				<%= @post.favorites.count %> いいね
				<% end %>
				<% end %>

				<h2>コメント</h2>
				<table class="table table-hover table-inverse">
					<table style="border:none; table-layout: fixed; width: 100%;">
						<colgroup>
							<col style="width:100%;">
						</colgroup>
						<tbody>
							<tr>
								<td>
									<%= form_for [@post, @post_comment] do |f| %>
									<%= f.text_area :body, :size=>"100x5", class: "form-control",placeholder: "コメントをここに" %>
									<%= f.submit "送信する", class: "btn btn-primary pull-right" %>
									<% end %>
								</td>
							</tr>
							<tr>
								<td style="word-wrap: break-word;">
									<% @post.post_comments.each do |post_comment| %>
									<h3>
										<%= post_comment.user.name %>　　<%= post_comment.body %>
										<% if current_user.admin? || (post_comment.user == current_user) %>
										<%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, class: "btn btn-danger pull-right" %>
										<% end %>
										<% end %>
									</h3>
								</td>
							</tr>
						</tbody>
					</table>
				</table>
			</div>
		</div>
	</div>
</div>